function AuthScreen({ onAuthenticated }: { onAuthenticated: () => void }) {
  const [signup, setSignup] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async () => { setLoading(true); setError(''); try { const response = signup ? await register({ name, email, password }) : await login({ email, password }); localStorage.setItem('studyflow-token', response.token); onAuthenticated() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to sign in') } finally { setLoading(false) } }
  return <main className="auth-screen"><section className="auth-card"><div className="brand-mark"><GraduationCap size={21} /></div><p className="eyebrow">SMART STUDY PLANNER</p><h1>Plan smart.<br /><span>Study better.</span></h1><p className="auth-copy">A quieter way to make your progress visible.</p>{signup && <label>Name<input value={name} onChange={event => setName(event.target.value)} placeholder="Alex Morgan" /></label>}<label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="you@example.com" /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="At least 8 characters" /></label>{error && <p className="auth-error">{error}</p>}<button className="primary-button auth-submit" onClick={submit} disabled={loading}>{loading ? 'Connecting...' : signup ? 'Create account' : 'Sign in'} <ChevronRight size={17} /></button><button className="text-button auth-switch" onClick={() => { setSignup(!signup); setError('') }}>{signup ? 'Already have an account? Sign in' : 'New to SESSION-SCHEDULAR? Create an account'}</button><button className="secondary-button demo-button" onClick={() => { localStorage.setItem('studyflow-token', 'demo'); onAuthenticated() }}>Continue with demo data</button></section></main>
}
import { useEffect, useState } from 'react'
import { Activity, ChevronRight, BarChart3, BookOpen, CalendarDays, Check, Clock3, Download, Flame, GraduationCap, LayoutDashboard, Menu, MessageCircle, Moon, Pause, Play, Plus, Search, Settings as SettingsIcon, Sparkles, Sun, Target, TimerReset, Trash2, Trophy, UserRound, X } from 'lucide-react'
import './App.css'
import { askStudyAgent, createSession, deleteSession, getProfile, getSessions, login, register, updateProfile, updateSession } from './api'

type Page = 'Dashboard' | 'Sessions' | 'Subjects' | 'Goals' | 'Pomodoro' | 'Statistics' | 'Calendar' | 'Suggestions' | 'Achievements' | 'Profile' | 'Settings' | 'AI Assistant'
type Session = { id: number; subject: string; minutes: number; date: string; mode: string; notes: string }
type Subject = { id: number; name: string; color: string }
const today = new Date().toISOString().slice(0, 10)
const seed: Session[] = [{ id: 1, subject: 'Data Structures', minutes: 78, date: today, mode: 'Revision', notes: 'Trees and graph traversal' }, { id: 2, subject: 'Java Programming', minutes: 52, date: today, mode: 'Pomodoro', notes: 'Interfaces and collections' }, { id: 3, subject: 'Mathematics', minutes: 64, date: today, mode: 'Normal Study', notes: 'Discrete probability' }]
const subjectsSeed: Subject[] = [{ id: 1, name: 'Data Structures', color: '#ef8354' }, { id: 2, name: 'Java Programming', color: '#456990' }, { id: 3, name: 'Mathematics', color: '#49a078' }, { id: 4, name: 'Computer Organization', color: '#8a5cf6' }]
const time = (n: number) => `${Math.floor(n / 60)}h ${n % 60}m`
const date = (v: string) => new Date(`${v}T12:00:00`).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })

export function App() {
  const [authenticated, setAuthenticated] = useState(() => localStorage.getItem('studyflow-token') === 'demo')
  const [page, setPage] = useState<Page>('Dashboard'); const [sessions, setSessions] = useState<Session[]>(() => JSON.parse(localStorage.getItem('sessions') || JSON.stringify(seed))); const [subjects] = useState<Subject[]>(() => JSON.parse(localStorage.getItem('subjects') || JSON.stringify(subjectsSeed))); const [goal, setGoal] = useState(180); const [form, setForm] = useState(false); const [query, setQuery] = useState(''); const [dark, setDark] = useState(false); const [menu, setMenu] = useState(false); const [message, setMessage] = useState(''); const [seconds, setSeconds] = useState(1500); const [running, setRunning] = useState(false)
  useEffect(() => localStorage.setItem('sessions', JSON.stringify(sessions)), [sessions]); useEffect(() => { if (authenticated && localStorage.getItem('studyflow-token') !== 'demo') { getProfile().then(profile => { setGoal(profile.goal); localStorage.setItem('session-profile', JSON.stringify(profile)) }).catch(() => setMessage('Using local profile while the API is unavailable')); getSessions().then(remote => setSessions(remote.map(session => ({ ...session, id: Number(session.id) || Date.now() })))).catch(() => setMessage('Using local study history while the API is unavailable')) } }, [authenticated]); useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light' }, [dark]); useEffect(() => { if (!running) return; const id = window.setInterval(() => setSeconds(s => s > 0 ? s - 1 : 0), 1000); return () => clearInterval(id) }, [running])
  const todayMinutes = sessions.filter(s => s.date === today).reduce((a, s) => a + s.minutes, 0); const total = sessions.reduce((a, s) => a + s.minutes, 0); const progress = Math.min(100, Math.round(todayMinutes / goal * 100)); const filtered = sessions.filter(s => `${s.subject} ${s.mode}`.toLowerCase().includes(query.toLowerCase())); const notify = (m: string) => { setMessage(m); window.setTimeout(() => setMessage(''), 2200) }; const nav: [Page, typeof LayoutDashboard][] = [['Dashboard', LayoutDashboard], ['Sessions', Clock3], ['Subjects', BookOpen], ['Goals', Target], ['Pomodoro', TimerReset], ['Statistics', BarChart3], ['Calendar', CalendarDays], ['Suggestions', Sparkles], ['Achievements', Trophy], ['Profile', UserRound], ['Settings', SettingsIcon], ['AI Assistant', MessageCircle]]
  const exportData = () => { const csv = ['Subject,Duration,Date,Mode,Notes', ...sessions.map(s => `${s.subject},${s.minutes},${s.date},${s.mode},"${s.notes}"`)].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'study-history.csv'; link.click(); notify('CSV exported') }
  const persistSession = async (session: Omit<Session, 'id'>, editingId?: number) => { if (localStorage.getItem('studyflow-token') !== 'demo') { try { const saved = editingId ? await updateSession(editingId, session) : await createSession(session); setSessions(current => editingId ? current.map(item => item.id === editingId ? { ...saved, id: editingId } : item) : [{ ...saved, id: Number(saved.id) || Date.now() }, ...current]); setForm(false); notify(editingId ? 'Session updated' : 'Session saved to your account'); return } catch { notify('Saved locally; API unavailable') } } setSessions(current => editingId ? current.map(item => item.id === editingId ? { ...session, id: editingId } : item) : [{ ...session, id: Date.now() }, ...current]); setForm(false); notify(editingId ? 'Session updated' : 'Session saved') }
  const removePersistedSession = async (id: number) => { if (localStorage.getItem('studyflow-token') !== 'demo') { try { await deleteSession(id) } catch { notify('Could not sync deletion') } } setSessions(current => current.filter(s => s.id !== id)); notify('Session deleted') }
  useEffect(() => { if (message === 'Logged out for this demo') { localStorage.removeItem('studyflow-token'); localStorage.removeItem('session-profile'); setAuthenticated(false) } }, [message])
  if (!authenticated) return <AuthScreen onAuthenticated={() => setAuthenticated(true)} />
  if (page === 'AI Assistant') return <main className="agent-page"><StudyAgent sessions={sessions} goal={goal} progress={progress} /></main>
  return <div className="app-shell"><aside className={`sidebar ${menu ? 'open' : ''}`}><div className="brand"><div className="brand-mark"><GraduationCap size={20} /></div><div><strong>session<span>schedular</span></strong><small>SMART STUDY PLANNER</small></div></div><p className="label">WORKSPACE</p><nav>{nav.slice(0, 7).map(([name, Icon]) => <button className={page === name ? 'active' : ''} key={name} onClick={() => { setPage(name); setMenu(false) }}><Icon size={18} />{name}</button>)}</nav><p className="label">PERSONAL</p><nav>{nav.slice(7).map(([name, Icon]) => <button className={page === name ? 'active' : ''} key={name} onClick={() => { setPage(name); setMenu(false) }}><Icon size={18} />{name}</button>)}</nav><div className="sidebar-bottom"><div className="mini-profile"><span className="avatar">AM</span><div><strong>Alex Morgan</strong><small>Student account</small></div></div><button className="logout" onClick={() => notify('Logged out for this demo')}>Log out</button></div></aside><main><header className="topbar"><button className="icon-button menu-button" onClick={() => setMenu(!menu)} aria-label="Open menu"><Menu size={20} /></button><span className="breadcrumb">Workspace / <b>{page}</b></span><button className="icon-button" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Sun size={18} /> : <Moon size={18} />}</button></header><div className="page-wrap"><Header page={page} add={() => setForm(true)} />{page === 'Dashboard' && <Dashboard today={todayMinutes} goal={goal} progress={progress} sessions={sessions} subjects={subjects} go={setPage} />}{page === 'Sessions' && <Sessions sessions={filtered} query={query} setQuery={setQuery} add={() => setForm(true)} remove={(id: number) => { removePersistedSession(id) }} exportData={exportData} />}{page === 'Subjects' && <Subjects subjects={subjects} sessions={sessions} />}{page === 'Goals' && <Goals goal={goal} setGoal={setGoal} today={todayMinutes} progress={progress} total={total} />}{page === 'Pomodoro' && <Timer seconds={seconds} running={running} toggle={() => setRunning(!running)} reset={() => { setRunning(false); setSeconds(1500) }} />}{page === 'Statistics' && <Stats sessions={sessions} total={total} subjects={subjects} />}{page === 'Calendar' && <Calendar sessions={sessions} />}{page === 'Suggestions' && <Suggestions />}{page === 'Achievements' && <Achievements total={total} count={sessions.length} />}{page === 'Profile' && <Profile total={total} count={sessions.length} />}{page === 'Settings' && <Settings dark={dark} setDark={setDark} exportData={exportData} />}</div></main>{form && <Modal subjects={subjects} close={() => setForm(false)} save={(s: Omit<Session, 'id'>) => { persistSession(s) }} />}{message && <div className="toast"><Check size={16} />{message}</div>}</div>
}
function Header({ page, add }: { page: Page; add: () => void }) { return <div className="page-heading"><div><p className="eyebrow">SUNDAY, AUGUST 23, 2026</p><h1>{page === 'Dashboard' ? <>Good morning, Alex <span className="wave">✦</span></> : page}</h1><p className="subheading">{page === 'Dashboard' ? 'A clear plan makes room for deep work.' : 'Make progress visible, one intentional block at a time.'}</p></div>{['Dashboard', 'Sessions'].includes(page) && <button className="primary-button" onClick={add}><Plus size={18} /> Add session</button>}</div> }
function Card({ icon, label, value, note, color }: any) { return <div className="metric-card"><div className={`metric-icon ${color}`}>{icon}</div><p>{label}</p><strong>{value}</strong><small>{note}</small></div> }
function Dashboard({ today, goal, progress, sessions, subjects, go }: any) { return <><div className="metric-grid"><Card icon={<Clock3 />} label="Today's study time" value={time(today)} note="+18% from yesterday" color="orange" /><Card icon={<Target />} label="Daily goal" value={time(goal)} note={`${progress}% complete`} color="blue" /><Card icon={<Flame />} label="Current streak" value="7 days" note="Best: 14 days" color="green" /><Card icon={<Activity />} label="Productivity" value="86 / 100" note="Based on your ratings" color="purple" /></div><div className="dashboard-grid"><section className="panel activity"><div className="panel-title"><div><p className="eyebrow">CONSISTENCY</p><h2>Weekly activity</h2></div><button className="text-button" onClick={() => go('Statistics')}>View statistics</button></div><div className="bars">{[48, 68, 38, 82, 55, 92, progress].map((h: number, i: number) => <div key={i}><span style={{ height: `${h}%` }} /><small>{['M', 'T', 'W', 'T', 'F', 'S', 'S'][i]}</small></div>)}</div></section><section className="panel progress"><p className="eyebrow">TODAY'S FOCUS</p><h2>Goal progress</h2><div className="progress-ring"><b>{progress}%</b></div><p>{progress >= 100 ? 'Daily goal completed. Great job!' : `${time(Math.max(0, goal - today))} left to reach your goal`}</p><button className="secondary-button full" onClick={() => go('Goals')}>Manage goals</button></section></div><div className="dashboard-grid"><section className="panel"><div className="panel-title"><div><p className="eyebrow">BREAKDOWN</p><h2>Top subjects</h2></div><button className="text-button" onClick={() => go('Subjects')}>See all</button></div>{subjects.slice(0, 3).map((s: Subject) => <div className="subject-row" key={s.id}><i style={{ background: s.color }} /> <strong>{s.name}</strong><span>{time(sessions.filter((x: Session) => x.subject === s.name).reduce((a: number, x: Session) => a + x.minutes, 0))}</span></div>)}</section><section className="panel suggestion"><Sparkles size={25} /><p className="eyebrow">SMART SUGGESTION</p><h2>Protect your best focus hours.</h2><p>Your sessions are strongest before noon. Schedule the hardest subject first tomorrow.</p><button className="text-button" onClick={() => go('Suggestions')}>Open suggestions</button></section></div></> }
export function SessionsLegacy({ sessions, query, setQuery, remove, exportData }: any) { return <section className="panel sessions"><div className="toolbar"><div className="search"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search subjects or modes" /></div><button className="secondary-button" onClick={exportData}><Download size={16} /> Export CSV</button></div>{sessions.map((s: Session) => <div className="session-row" key={s.id}><div><strong>{s.subject}</strong><small>{s.mode} · {date(s.date)} · {s.notes}</small></div><b>{time(s.minutes)}</b><button className="icon-button danger" onClick={() => remove(s.id)} aria-label="Delete session"><Trash2 size={16} /></button></div>)}{!sessions.length && <div className="empty"><Search size={28} /><b>No sessions found</b><span>Try another search or add a new session.</span></div>}</section> }

function Sessions({ sessions, query, setQuery, remove, exportData }: any) {
  const edit = async (session: Session) => {
    const minutes = Number(window.prompt('Duration in minutes', String(session.minutes)))
    if (!Number.isFinite(minutes) || minutes <= 0) return
    const notes = window.prompt('Notes', session.notes) ?? session.notes
    const updated = { ...session, minutes, notes }
    if (localStorage.getItem('studyflow-token') !== 'demo') {
      try { await updateSession(session.id, updated); window.location.reload() } catch { window.alert('Could not update this session') }
      return
    }
    localStorage.setItem('sessions', JSON.stringify(JSON.parse(localStorage.getItem('sessions') || '[]').map((item: Session) => item.id === session.id ? updated : item)))
    window.location.reload()
  }
  return <section className="panel sessions"><div className="toolbar"><div className="search"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search subjects or modes" /></div><button className="secondary-button" onClick={exportData}><Download size={16} /> Export CSV</button></div>{sessions.map((s: Session) => <div className="session-row" key={s.id}><div><strong>{s.subject}</strong><small>{s.mode} · {date(s.date)} · {s.notes}</small></div><b>{time(s.minutes)}</b><button className="text-button" onClick={() => edit(s)}>Edit</button><button className="icon-button danger" onClick={() => remove(s.id)} aria-label="Delete session"><Trash2 size={16} /></button></div>)}{!sessions.length && <div className="empty"><Search size={28} /><b>No sessions found</b><span>Try another search or add a new session.</span></div>}</section>
}
function Subjects({ subjects, sessions }: any) { return <div className="subject-cards">{subjects.map((s: Subject) => <article className="subject-card" key={s.id}><span style={{ background: s.color }}>{s.name.slice(0, 2)}</span><div><h2>{s.name}</h2><p>{time(sessions.filter((x: Session) => x.subject === s.name).reduce((a: number, x: Session) => a + x.minutes, 0))} studied</p></div><ChevronRight size={18} /></article>)}</div> }
function Goals({ goal, setGoal, today, progress, total }: any) { const saveGoal = async (value: number) => { setGoal(value); if (localStorage.getItem('studyflow-token') !== 'demo' && value >= 15) { const profile = JSON.parse(localStorage.getItem('session-profile') || '{}'); try { const updated = await updateProfile({ name: profile.name || 'Alex Morgan', email: profile.email || 'alex@ssp.local', goal: value }); localStorage.setItem('session-profile', JSON.stringify(updated)) } catch { /* local state remains usable while offline */ } } }; return <section className="panel goal-panel"><p className="eyebrow">DAILY TARGET</p><h2>Build a repeatable rhythm</h2><div className="big-progress"><span style={{ width: `${progress}%` }} /></div><div className="goal-numbers"><b>{time(today)}<small>Studied today</small></b><b>{time(goal)}<small>Daily goal</small></b><b>{progress}%<small>Complete</small></b></div><label>Daily goal in minutes<input type="number" min="15" value={goal} onChange={e => saveGoal(Number(e.target.value))} /></label><p>{time(total)} logged across your study history.</p></section> }
function Timer({ seconds, running, toggle, reset }: any) { return <section className="panel timer"><p className="eyebrow">DEEP WORK MODE</p><h2>One clear block at a time.</h2><div className="timer-face"><small>Focus</small><b>{String(Math.floor(seconds / 60)).padStart(2, '0')}:{String(seconds % 60).padStart(2, '0')}</b></div><button className="primary-button" onClick={toggle}>{running ? <Pause /> : <Play />}{running ? 'Pause' : 'Start focus'}</button><button className="secondary-button" onClick={reset}>Reset</button></section> }
function Stats({ sessions, total, subjects }: any) { return <><div className="metric-grid"><Card icon={<Clock3 />} label="Total study time" value={time(total)} note="All logged sessions" color="orange" /><Card icon={<BarChart3 />} label="Average session" value={`${sessions.length ? Math.round(total / sessions.length) : 0} min`} note="Across all sessions" color="blue" /></div><section className="panel"><p className="eyebrow">DISTRIBUTION</p><h2>Subject balance</h2>{subjects.map((s: Subject) => <div className="stat-bar" key={s.id}><span>{s.name}</span><b>{time(sessions.filter((x: Session) => x.subject === s.name).reduce((a: number, x: Session) => a + x.minutes, 0))}</b></div>)}</section></> }
function Calendar({ sessions }: any) { return <section className="panel calendar"><p className="eyebrow">YOUR RHYTHM</p><h2>August 2026</h2><div>{Array.from({ length: 31 }, (_, i) => <span className={sessions.some((s: Session) => s.date === `2026-08-${String(i + 1).padStart(2, '0')}`) ? 'studied' : ''} key={i}>{i + 1}</span>)}</div></section> }
function Suggestions() { return <div className="suggestion-grid"><section className="panel suggestion-card"><Sparkles /><p className="eyebrow">SUGGESTION</p><h2>Make space for a break</h2><p>Your recent blocks are strong. Consider a short break before your next one.</p></section><section className="panel suggestion-card"><Target /><p className="eyebrow">SUGGESTION</p><h2>Keep the goal within reach</h2><p>A focused 25-minute block would move your daily goal forward.</p></section></div> }
function StudyAgent({ sessions, goal, progress }: { sessions: Session[]; goal: number; progress: number }) {
  const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [messages, setMessages] = useState<{ role: 'agent' | 'user'; text: string }[]>([{ role: 'agent', text: 'I am your SESSION-SCHEDULAR study agent. Ask me about your plan, focus time, subjects, or next best session.' }])
  const respond = (question: string) => { const lower = question.toLowerCase(); const total = sessions.reduce((sum, session) => sum + session.minutes, 0); const subject = sessions.reduce<Record<string, number>>((all, session) => ({ ...all, [session.subject]: (all[session.subject] || 0) + session.minutes }), {}); const top = Object.entries(subject).sort((a, b) => b[1] - a[1])[0]; if (lower.includes('progress') || lower.includes('goal')) return `You are ${progress}% through today's ${goal}-minute goal. ${Math.max(0, goal - sessions.filter(session => session.date === today).reduce((sum, session) => sum + session.minutes, 0))} minutes remain.`; if (lower.includes('subject') || lower.includes('study')) return `${top ? `${top[0]} is currently your strongest subject at ${top[1]} minutes.` : 'Start by logging a subject you want to work on.'} A focused 25-minute block is a good next step.`; if (lower.includes('break') || lower.includes('tired')) return 'Your best plan includes a short break after a focused block. Try five minutes away from the screen, then reassess.'; return `You have logged ${Math.floor(total / 60)}h ${total % 60}m so far. I suggest choosing one concrete task, setting the Pomodoro timer, and logging the result.` }
  const send = async (value = input) => { if (!value.trim() || loading) return; const question = value.trim(); setMessages(current => [...current, { role: 'user', text: question }]); setInput(''); setLoading(true); if (localStorage.getItem('studyflow-token') !== 'demo') { try { const result = await askStudyAgent(question, { goal, progress, sessions }); setMessages(current => [...current, { role: 'agent', text: result.reply }]); setLoading(false); return } catch { /* use local guidance when the provider is not configured */ } } setMessages(current => [...current, { role: 'agent', text: respond(question) }]); setLoading(false) }
  return <><Header page="AI Assistant" add={() => undefined} /><section className="agent-shell panel"><div className="agent-head"><div className="agent-avatar"><Sparkles size={18} /></div><div><h2>Study Agent</h2><p>Context-aware planning, right inside your logbook.</p></div><span className="agent-status"><i /> Online</span></div><div className="agent-messages">{messages.map((message, index) => <div className={`agent-message ${message.role}`} key={index}><span>{message.role === 'agent' ? '✦' : 'You'}</span><p>{message.text}</p></div>)}{loading && <div className="agent-message"><span>✦</span><p>Thinking about your study context...</p></div>}</div><div className="agent-prompts"><button onClick={() => send('How is my progress?')}>How is my progress?</button><button onClick={() => send('What subject should I study?')}>What should I study?</button><button onClick={() => send('When should I take a break?')}>When should I take a break?</button></div><form className="agent-input" onSubmit={event => { event.preventDefault(); send() }}><input value={input} onChange={event => setInput(event.target.value)} placeholder="Message your study agent..." aria-label="Message your study agent" /><button className="primary-button" type="submit" disabled={loading}><ChevronRight size={18} /></button></form></section></>
}
function Achievements({ total, count }: any) { return <div className="achievement-grid">{[['First session', count > 0], ['10 sessions', count >= 10], ['10 hours studied', total >= 600], ['7 day streak', false]].map(([name, unlocked]) => <article className={`achievement ${unlocked ? 'unlocked' : ''}`} key={String(name)}><Trophy /><div><h2>{name}</h2><p>{unlocked ? 'Unlocked' : 'Keep building your rhythm'}</p></div></article>)}</div> }
function Profile({ total, count }: any) { const stored = JSON.parse(localStorage.getItem('session-profile') || '{}'); const [name, setName] = useState(stored.name || 'Alex Morgan'); const [email, setEmail] = useState(stored.email || 'alex@ssp.local'); const save = async () => { if (localStorage.getItem('studyflow-token') !== 'demo') { try { const updated = await updateProfile({ name, email, goal: stored.goal || 180 }); localStorage.setItem('session-profile', JSON.stringify(updated)) } catch { return } } }; return <section className="panel profile"><div className="avatar large">AM</div><h2>Profile</h2><label>Name<input value={name} onChange={e => setName(e.target.value)} /></label><label>Email<input value={email} onChange={e => setEmail(e.target.value)} /></label><button className="primary-button" onClick={save}>Save profile</button><div className="profile-stats"><b>{time(total)}<small>Total study time</small></b><b>{count}<small>Sessions logged</small></b><b>7 days<small>Current streak</small></b></div></section> }
function Settings({ dark, setDark, exportData }: any) { return <section className="panel settings"><div><strong>Appearance</strong><p>Choose a calm workspace</p><button className="segmented" onClick={() => setDark(!dark)}>{dark ? <Moon /> : <Sun />} {dark ? 'Dark mode' : 'Light mode'}</button></div><div><strong>Your data</strong><p>Download a portable copy</p><button className="secondary-button" onClick={exportData}><Download size={16} /> Export CSV</button></div></section> }
function Modal({ subjects, close, save }: any) { const [subject, setSubject] = useState(subjects[0]?.name || ''); const [minutes, setMinutes] = useState(25); const [mode, setMode] = useState('Normal Study'); const [notes, setNotes] = useState(''); return <div className="modal-backdrop"><div className="modal"><button className="icon-button close" onClick={close}><X /></button><p className="eyebrow">NEW LOG ENTRY</p><h2>Add study session</h2><label>Subject<select value={subject} onChange={e => setSubject(e.target.value)}>{subjects.map((s: Subject) => <option key={s.id}>{s.name}</option>)}</select></label><label>Duration<input type="number" min="1" value={minutes} onChange={e => setMinutes(Number(e.target.value))} /></label><label>Mode<select value={mode} onChange={e => setMode(e.target.value)}>{['Normal Study', 'Pomodoro', 'Revision', 'Assignment'].map(x => <option key={x}>{x}</option>)}</select></label><label>Notes<textarea value={notes} onChange={e => setNotes(e.target.value)} /></label><div className="modal-actions"><button className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" onClick={() => save({ subject, minutes, date: today, mode, notes })}>Save session <Check size={16} /></button></div></div></div> }




